mod avif_format;
mod bmp_format;
mod cr2_format;
mod gif_format;
mod heif_format;
mod ico_format;
mod jpeg_format;
mod jpeg2000_format;
mod jxl_format;
mod jxr_format;
mod ora_format;
mod png_format;
mod psd_format;
mod tiff_format;
mod webp_format;

pub use self::avif_format::AvifFormat;
pub use self::bmp_format::BmpFormat;
pub use self::cr2_format::Cr2Format;
pub use self::gif_format::GifFormat;
pub use self::heif_format::HeifFormat;
pub use self::ico_format::IcoFormat;
pub use self::jpeg_format::JpegFormat;
pub use self::jpeg2000_format::Jpeg2000Format;
pub use self::jxl_format::JxlFormat;
pub use self::jxr_format::JxrFormat;
pub use self::ora_format::OraFormat;
pub use self::png_format::PngFormat;
pub use self::psd_format::PsdFormat;
pub use self::tiff_format::TiffFormat;
pub use self::webp_format::WebpFormat;