mod avif_detector;
mod bmp_detector;
mod cr2_detector;
mod gif_detector;
mod heif_detector;
mod ico_detector;
mod jpeg_detector;
mod jpeg2000_detector;
mod jxl_detector;
mod jxr_detector;
mod ora_detector;
mod png_detector;
mod psd_detector;
mod tiff_detector;
mod webp_detector;

pub use self::avif_detector::AvifDetector;
pub use self::bmp_detector::BmpDetector;
pub use self::cr2_detector::Cr2Detector;
pub use self::gif_detector::GifDetector;
pub use self::heif_detector::HeifDetector;
pub use self::ico_detector::IcoDetector;
pub use self::jpeg_detector::JpegDetector;
pub use self::jpeg2000_detector::Jpeg2000Detector;
pub use self::jxl_detector::JxlDetector;
pub use self::jxr_detector::JxrDetector;
pub use self::ora_detector::OraDetector;
pub use self::png_detector::PngDetector;
pub use self::psd_detector::PsdDetector;
pub use self::tiff_detector::TiffDetector;
pub use self::webp_detector::WebpDetector;