mod coff_detector;
mod coff_i386_detector;
mod coff_ia64_detector;
mod coff_x64_detector;
mod der_detector;
mod dex_detector;
mod dey_detector;
mod dll_detector;
mod elf_detector;
mod exe_detector;
mod java_detector;
mod llvm_detector;
mod mach_detector;
mod nes_detector;
mod pem_detector;
mod wasm_detector;

pub use self::coff_detector::CoffDetector;
pub use self::coff_i386_detector::Coff_i386Detector;
pub use self::coff_ia64_detector::Coff_ia64Detector;
pub use self::coff_x64_detector::Coff_x64Detector;
pub use self::der_detector::DerDetector;
pub use self::dex_detector::DexDetector;
pub use self::dey_detector::DeyDetector;
pub use self::dll_detector::DllDetector;
pub use self::elf_detector::ElfDetector;
pub use self::exe_detector::ExeDetector;
pub use self::java_detector::JavaDetector;
pub use self::llvm_detector::LlvmDetector;
pub use self::mach_detector::MachDetector;
pub use self::nes_detector::NesDetector;
pub use self::pem_detector::PemDetector;
pub use self::wasm_detector::WasmDetector;